# Site settings
email: "jgranthamburton@gmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Jamie Grantham-Burton
description:
url: ""
# twitter_username: ""
default_img:
home_img: "https://unsplash.com/search/hong?photo=ujPOfVJ7i3I"

# Profile settings
name: Jamie Grantham-Burton
profile_img: "http://i1174.photobucket.com/albums/r613/jgburton/_MG_0689_zpsw6pxwu0u.jpg"
profile: "I'm a Full Stack Web Developer based in London from Derbyshire via Hong Kong. I have a background in Music and also work as a guitarist and teacher."
social:
  # twitter:
  github: "https://www.github.com/jgburton"
  linkedin: "https://www.linkedin.com/in/jgranthamburton/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
